In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
train_dataset=pd.read_csv('/content/drive/MyDrive/Titanic-dataset/train.csv')
test_dataset=pd.read_csv('/content/drive/MyDrive/Titanic-dataset/test.csv')

In [4]:
titanic_train=train_dataset.copy()
titanic_test=test_dataset.copy()

In [5]:
og_train=train_dataset.copy()
og_test=test_dataset.copy()

In [6]:
train_dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
train_dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
train_dataset['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [10]:
import re

In [11]:
data=train_dataset['Cabin'].str.extract(r'([a-zA-Z])',expand=False)

In [12]:
data.value_counts()

Cabin
C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: count, dtype: int64

In [13]:
train_dataset[train_dataset.loc[:,'Cabin']=='T']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
339,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5,T,S

In [14]:
train_dataset['Ticket']

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [15]:
train_dataset['Ticket'].str.extract(r'(?:\d+)*(\w+[\.]?[\/]?\w+[\.]?)\s*(\d+)*',expand=False)

            0        1
0         A/5    21171
1          PC    17599
2    STON/O2.  3101282
3          03      NaN
4          50      NaN
..        ...      ...
886        36      NaN
887        53      NaN
888     W./C.     6607
889        69      NaN
890        76      NaN

[891 rows x 2 columns]

In [16]:
print(train_dataset['Name'].to_string())

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
5                                       Moran, Mr. James
6                                McCarthy, Mr. Timothy J
7                         Palsson, Master. Gosta Leonard
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
12                        Saundercock, Mr. William Henry
13                           Andersson, Mr. Anders Johan
14                  Vestrom, Miss. Hulda Amanda Adolfina
15                       Hewlett, Mrs. (Mary D Kingcome)
16                                  Rice, Master. Eugene
17                          Williams, Mr. Charles Eugene
18     Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                               Masselmani, Mrs. Fatima
20                                  Fynney, Mr. Joseph J
21                                 Beesley, Mr. Lawrence
22                           McGowan, Miss. Anna 'Annie'
23                          Sloper, Mr. William Thompson
24                         Palsson, Miss. Torborg Danira
25     Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
26                               Emir, Mr. Farred Chehab
27                        Fortune, Mr. Charles Alexander
28                         O'Dwyer, Miss. Ellen 'Nellie'
29                                   Todoroff, Mr. Lalio
30                              Uruchurtu, Don. Manuel E
31        Spencer, Mrs. William Augustus (Marie Eugenie)
32                              Glynn, Miss. Mary Agatha
33                                 Wheadon, Mr. Edward H
34                               Meyer, Mr. Edgar Joseph
35                        Holverson, Mr. Alexander Oskar
36                                      Mamee, Mr. Hanna
37                              Cann, Mr. Ernest Charles
38                    Vander Planke, Miss. Augusta Maria
39                           Nicola-Yarred, Miss. Jamila
40        Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
41     Turpin, Mrs. William John Robert (Dorothy Ann ...
42                                   Kraeff, Mr. Theodor
43              Laroche, Miss. Simonne Marie Anne Andree
44                         Devaney, Miss. Margaret Delia
45                              Rogers, Mr. William John
46                                     Lennon, Mr. Denis
47                             O'Driscoll, Miss. Bridget
48                                   Samaan, Mr. Youssef
49         Arnold-Franchi, Mrs. Josef (Josefine Franchi)
50                            Panula, Master. Juha Niilo
51                          Nosworthy, Mr. Richard Cater
52              Harper, Mrs. Henry Sleeper (Myna Haxtun)
53     Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...
54                        Ostby, Mr. Engelhart Cornelius
55                                     Woolner, Mr. Hugh
56                                     Rugg, Miss. Emily
57                                   Novel, Mr. Mansouer
58                          West, Miss. Constance Mirium
59                    Goodwin, Master. William Frederick
60                                 Sirayanian, Mr. Orsen
61                                   Icard, Miss. Amelie
62                           Harris, Mr. Henry Birkhardt
63                                 Skoog, Master. Harald
64                                 Stewart, Mr. Albert A
65                              Moubarek, Master. Gerios
66                          Nye, Mrs. (Elizabeth Ramell)
67                              Crease, Mr. Ernest James
68                       Andersson, Miss. Erna Alexandra
69                                     Kink, Mr. Vincenz
70                            Jenkin, Mr. Stephen Curnow
71                            Goodwin, Miss. Lillian Amy
72                                  Hood, Mr. Ambrose Jr
73                           Chronopoulos, Mr. Apostolos
74                                         Bing, Mr. Lee
75                               Moen, Mr. Sigurd Hansen
76                                     Staneff, Mr. Ivan
77                              Moutal, Mr. Rahamin Haim
78                         Caldwell, Master. Alden Gates
79                              Dowdell, Miss. Elizabeth
80                                  Waelens, Mr. Achille
81                           Sheerlinck, Mr. Jan Baptist
82                        McDermott, Miss. Brigdet Delia
83                               Carrau, Mr. Francisco M
84                                   Ilett, Miss. Bertha
85     Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...
86                                Ford, Mr. William Neal
87                         Slocovski, Mr. Selman Francis
88                            Fortune, Miss. Mabel Helen
89                                Celotti, Mr. Francesco
90                                  Christmann, Mr. Emil
91                            Andreasson, Mr. Paul Edvin
92                           Chaffee, Mr. Herbert Fuller
93                               Dean, Mr. Bertram Frank
94                                     Coxon, Mr. Daniel
95                           Shorney, Mr. Charles Joseph
96                             Goldschmidt, Mr. George B
97                       Greenfield, Mr. William Bertram
98                  Doling, Mrs. John T (Ada Julia Bone)
99                                     Kantor, Mr. Sinai
100                              Petranec, Miss. Matilda
101                     Petroff, Mr. Pastcho ('Pentcho')
102                            White, Mr. Richard Frasar
103                           Johansson, Mr. Gustaf Joel
104                       Gustafsson, Mr. Anders Vilhelm
105                                Mionoff, Mr. Stoytcho
106                     Salkjelsvik, Miss. Anna Kristine
107                               Moss, Mr. Albert Johan
108                                      Rekic, Mr. Tido
109                                  Moran, Miss. Bertha
110                       Porter, Mr. Walter Chamberlain
111                                 Zabour, Miss. Hileni
112                               Barton, Mr. David John
113                              Jussila, Miss. Katriina
114                                Attalah, Miss. Malake
115                                Pekoniemi, Mr. Edvard
116                                 Connors, Mr. Patrick
117                      Turpin, Mr. William John Robert
118                             Baxter, Mr. Quigg Edmond
119                    Andersson, Miss. Ellis Anna Maria
120                          Hickman, Mr. Stanley George
121                           Moore, Mr. Leonard Charles
122                                 Nasser, Mr. Nicholas
123                                  Webber, Miss. Susan
124                          White, Mr. Percival Wayland
125                         Nicola-Yarred, Master. Elias
126                                  McMahon, Mr. Martin
127                            Madsen, Mr. Fridtjof Arne
128                                    Peter, Miss. Anna
129                                   Ekstrom, Mr. Johan
130                                 Drazenoic, Mr. Jozef
131                       Coelho, Mr. Domingos Fernandeo
132       Robins, Mrs. Alexander A (Grace Charity Laury)
133        Weisz, Mrs. Leopold (Mathilde Francoise Pede)
134                       Sobey, Mr. Samuel James Hayden
135                                   Richard, Mr. Emile
136                         Newsom, Miss. Helen Monypeny
137                          Futrelle, Mr. Jacques Heath
138                                  Osen, Mr. Olaf Elon
139                                   Giglio, Mr. Victor
140                        Boulos, Mrs. Joseph (Sultana)
141                             Nysten, Miss. Anna Sofia
142    Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
143                                  Burke, Mr. Jeremiah
144                           Andrew, Mr. Edgardo Samuel
145                         Nicholls, Mr. Joseph Charles
146         Andersson, Mr. August Edvard ('Wennerstrom')
147                     Ford, Miss. Robina Maggie 'Ruby'
148             Navratil, Mr. Michel ('Louis M Hoffman')
149                    Byles, Rev. Thomas Roussel Davids
150                           Bateman, Rev. Robert James
151                    Pears, Mrs. Thomas (Edith Wearne)
152                                     Meo, Mr. Alfonzo
153                      van Billiard, Mr. Austin Blyler
154                                Olsen, Mr. Ole Martin
155                          Williams, Mr. Charles Duane
156                     Gilnagh, Miss. Katherine 'Katie'
157                                      Corn, Mr. Harry
158                                  Smiljanic, Mr. Mile
159                           Sage, Master. Thomas Henry
160                             Cribb, Mr. John Hatfield
161    Watt, Mrs. James (Elizabeth 'Bessie' Inglis Mi...
162                           Bengtsson, Mr. John Viktor
163                                      Calic, Mr. Jovo
164                         Panula, Master. Eino Viljami
165      Goldsmith, Master. Frank John William 'Frankie'
166               Chibnall, Mrs. (Edith Martha Bowerman)
167      Skoog, Mrs. William (Anna Bernhardina Karlsson)
168                                  Baumann, Mr. John D
169                                        Ling, Mr. Lee
170                            Van der hoef, Mr. Wyckoff
171                                 Rice, Master. Arthur
172                         Johnson, Miss. Eleanor Ileen
173                            Sivola, Mr. Antti Wilhelm
174                              Smith, Mr. James Clinch
175                               Klasen, Mr. Klas Albin
176                        Lefebre, Master. Henry Forbes
177                           Isham, Miss. Ann Elizabeth
178                                   Hale, Mr. Reginald
179                                  Leonard, Mr. Lionel
180                         Sage, Miss. Constance Gladys
181                                     Pernot, Mr. Rene
182                Asplund, Master. Clarence Gustaf Hugo
183                            Becker, Master. Richard F
184                  Kink-Heilmann, Miss. Luise Gretchen
185                                Rood, Mr. Hugh Roscoe
186      O'Brien, Mrs. Thomas (Johanna 'Hannah' Godfrey)
187        Romaine, Mr. Charles Hallace ('Mr C Rolmane')
188                                     Bourke, Mr. John
189                                  Turcin, Mr. Stjepan
190                                  Pinsky, Mrs. (Rosa)
191                                Carbines, Mr. William
192      Andersen-Jensen, Miss. Carla Christine Nielsine
193                           Navratil, Master. Michel M
194            Brown, Mrs. James Joseph (Margaret Tobin)
195                                 Lurette, Miss. Elise
196                                  Mernagh, Mr. Robert
197                     Olsen, Mr. Karl Siegwart Andreas
198                     Madigan, Miss. Margaret 'Maggie'
199               Yrois, Miss. Henriette ('Mrs Harbeck')
200                       Vande Walle, Mr. Nestor Cyriel
201                                  Sage, Mr. Frederick
202                           Johanson, Mr. Jakob Alfred
203                                 Youseff, Mr. Gerious
204                             Cohen, Mr. Gurshon 'Gus'
205                           Strom, Miss. Telma Matilda
206                           Backstrom, Mr. Karl Alfred
207                          Albimona, Mr. Nassef Cassem
208                            Carr, Miss. Helen 'Ellen'
209                                     Blank, Mr. Henry
210                                       Ali, Mr. Ahmed
211                           Cameron, Miss. Clear Annie
212                               Perkin, Mr. John Henry
213                          Givard, Mr. Hans Kristensen
214                                  Kiernan, Mr. Philip
215                              Newell, Miss. Madeleine
216                               Honkanen, Miss. Eliina
217                         Jacobsohn, Mr. Sidney Samuel
218                                Bazzani, Miss. Albina
219                                   Harris, Mr. Walter
220                       Sunderland, Mr. Victor Francis
221                                 Bracken, Mr. James H
222                              Green, Mr. George Henry
223                                 Nenkoff, Mr. Christo
224                         Hoyt, Mr. Frederick Maxfield
225                         Berglund, Mr. Karl Ivar Sven
226                            Mellors, Mr. William John
227                      Lovell, Mr. John Hall ('Henry')
228                            Fahlstrom, Mr. Arne Jonas
229                              Lefebre, Miss. Mathilde
230         Harris, Mrs. Henry Birkhardt (Irene Wallach)
231                             Larsson, Mr. Bengt Edvin
232                            Sjostedt, Mr. Ernst Adolf
233                       Asplund, Miss. Lillian Gertrud
234                    Leyson, Mr. Robert William Norman
235                         Harknett, Miss. Alice Phoebe
236                                    Hold, Mr. Stephen
237                     Collyer, Miss. Marjorie 'Lottie'
238                      Pengelly, Mr. Frederick William
239                               Hunt, Mr. George Henry
240                                Zabour, Miss. Thamine
241                       Murphy, Miss. Katherine 'Kate'
242                      Coleridge, Mr. Reginald Charles
243                        Maenpaa, Mr. Matti Alexanteri
244                                 Attalah, Mr. Sleiman
245                          Minahan, Dr. William Edward
246                Lindahl, Miss. Agda Thorilda Viktoria
247                      Hamalainen, Mrs. William (Anna)
248                        Beckwith, Mr. Richard Leonard
249                        Carter, Rev. Ernest Courtenay
250                               Reed, Mr. James George
251           Strom, Mrs. Wilhelm (Elna Matilda Persson)
252                            Stead, Mr. William Thomas
253                             Lobb, Mr. William Arthur
254             Rosblom, Mrs. Viktor (Helena Wilhelmina)
255              Touma, Mrs. Darwis (Hanne Youssef Razi)
256                       Thorne, Mrs. Gertrude Maybelle
257                                 Cherry, Miss. Gladys
258                                     Ward, Miss. Anna
259                          Parrish, Mrs. (Lutie Davis)
260                                    Smith, Mr. Thomas
261                    Asplund, Master. Edvin Rojj Felix
262                                    Taussig, Mr. Emil
263                                Harrison, Mr. William
264                                   Henry, Miss. Delia
265                                    Reeves, Mr. David
266                            Panula, Mr. Ernesti Arvid
267                             Persson, Mr. Ernst Ulrik
268        Graham, Mrs. William Thompson (Edith Junkins)
269                               Bissette, Miss. Amelia
270                                Cairns, Mr. Alexander
271                         Tornquist, Mr. William Henry
272            Mellinger, Mrs. (Elizabeth Anne Maidment)
273                                Natsch, Mr. Charles H
274                           Healy, Miss. Hanora 'Nora'
275                    Andrews, Miss. Kornelia Theodosia
276                    Lindblom, Miss. Augusta Charlotta
277                          Parkes, Mr. Francis 'Frank'
278                                   Rice, Master. Eric
279                     Abbott, Mrs. Stanton (Rosa Hunt)
280                                     Duane, Mr. Frank
281                     Olsson, Mr. Nils Johan Goransson
282                            de Pelsmaeker, Mr. Alfons
283                           Dorking, Mr. Edward Arthur
284                           Smith, Mr. Richard William
285                                  Stankovic, Mr. Ivan
286                              de Mulder, Mr. Theodore
287                                 Naidenoff, Mr. Penko
288                                 Hosono, Mr. Masabumi
289                                 Connolly, Miss. Kate
290                         Barber, Miss. Ellen 'Nellie'
291              Bishop, Mrs. Dickinson H (Helen Walton)
292                               Levy, Mr. Rene Jacques
293                                  Haas, Miss. Aloisia
294                                     Mineff, Mr. Ivan
295                                    Lewy, Mr. Ervin G
296                                   Hanna, Mr. Mansour
297                         Allison, Miss. Helen Loraine
298                                Saalfeld, Mr. Adolphe
299      Baxter, Mrs. James (Helene DeLaudeniere Chaput)
300             Kelly, Miss. Anna Katherine 'Annie Kate'
301                                   McCoy, Mr. Bernard
302                      Johnson, Mr. William Cahoone Jr
303                                  Keane, Miss. Nora A
304                    Williams, Mr. Howard Hugh 'Harry'
305                       Allison, Master. Hudson Trevor
306                              Fleming, Miss. Margaret
307    Penasco y Castellana, Mrs. Victor de Satode (M...
308                                  Abelson, Mr. Samuel
309                       Francatelli, Miss. Laura Mabel
310                       Hays, Miss. Margaret Bechstein
311                           Ryerson, Miss. Emily Borie
312                Lahtinen, Mrs. William (Anna Sylfven)
313                               Hendekovic, Mr. Ignjac
314                                   Hart, Mr. Benjamin
315                      Nilsson, Miss. Helmina Josefina
316                  Kantor, Mrs. Sinai (Miriam Sternin)
317                                 Moraweck, Dr. Ernest
318                             Wick, Miss. Mary Natalie
319    Spedden, Mrs. Frederic Oakley (Margaretta Corn...
320                                   Dennis, Mr. Samuel
321                                     Danoff, Mr. Yoto
322                            Slayter, Miss. Hilda Mary
323    Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...
324                             Sage, Mr. George John Jr
325                             Young, Miss. Marie Grice
326                            Nysveen, Mr. Johan Hansen
327                              Ball, Mrs. (Ada E Hall)
328       Goldsmith, Mrs. Frank John (Emily Alice Brown)
329                         Hippach, Miss. Jean Gertrude
330                                   McCoy, Miss. Agnes
331                                  Partner, Mr. Austen
332                            Graham, Mr. George Edward
333                      Vander Planke, Mr. Leo Edmondus
334    Frauenthal, Mrs. Henry William (Clara Heinshei...
335                                   Denkoff, Mr. Mitto
336                            Pears, Mr. Thomas Clinton
337                      Burns, Miss. Elizabeth Margaret
338                                Dahl, Mr. Karl Edwart
339                         Blackwell, Mr. Stephen Weart
340                       Navratil, Master. Edmond Roger
341                       Fortune, Miss. Alice Elizabeth
342                           Collander, Mr. Erik Gustaf
343           Sedgwick, Mr. Charles Frederick Waddington
344                              Fox, Mr. Stanley Hubert
345                        Brown, Miss. Amelia 'Mildred'
346                            Smith, Miss. Marion Elsie
347            Davison, Mrs. Thomas Henry (Mary E Finck)
348               Coutts, Master. William Loch 'William'
349                                     Dimic, Mr. Jovan

In [17]:
train_dataset['Title']=train_dataset['Name'].str.extract(r'\,\s+(\w+)')

In [18]:
train_dataset['Title'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the', 'Jonkheer'],
      dtype=object)

In [19]:
train_dataset.loc[train_dataset['Title'].isin(['Mlle','Ms']),'Title']='Miss'

In [20]:
train_dataset.loc[train_dataset['Title'].isin(['Major','Col','Capt']),'Title']='Army'

In [21]:
train_dataset.loc[train_dataset['Title'].isin(['Sir','Don','Jonkheer','Lady','the','Mme','Army','Rev','Dr']),'Title']='Rare'

In [22]:
train_dataset['Title'].value_counts()

Title
Mr        517
Miss      185
Mrs       125
Master     40
Rare       24
Name: count, dtype: int64

In [23]:
train_dataset['Name'].str.extract(r'(\w+)')

             0
0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
..         ...
886   Montvila
887     Graham
888   Johnston
889       Behr
890     Dooley

[891 rows x 1 columns]

In [24]:
train_dataset.drop(columns=['Name'],inplace=True)

In [25]:
train_dataset.loc[train_dataset['Parch'].isin([0,1,2])]['Survived'].value_counts()/len(train_dataset.loc[train_dataset['Parch'].isin([0,1,2])])
#after 0 rate to survive decreases , if people have their family members on board they will probably try to save them

Survived
0    0.614155
1    0.385845
Name: count, dtype: float64

In [26]:
train_dataset['Boogie']=train_dataset['Cabin'].str.extract(r'([a-zA-Z])')

In [27]:
train_dataset.groupby('Boogie')['Survived'].value_counts(normalize=True)

Boogie  Survived
A       0           0.533333
        1           0.466667
B       1           0.744681
        0           0.255319
C       1           0.593220
        0           0.406780
D       1           0.757576
        0           0.242424
E       1           0.750000
        0           0.250000
F       1           0.615385
        0           0.384615
G       0           0.500000
        1           0.500000
T       0           1.000000
Name: proportion, dtype: float64

In [28]:
pd.crosstab(
    train_dataset['Boogie'],
    train_dataset['Survived'],
    normalize='index'
) * 100

Survived           0          1
Boogie
A          53.333333  46.666667
B          25.531915  74.468085
C          40.677966  59.322034
D          24.242424  75.757576
E          25.000000  75.000000
F          38.461538  61.538462
G          50.000000  50.000000
T         100.000000   0.000000

In [29]:
train_dataset.loc[train_dataset['Boogie'].isin(['T']),'Boogie']=train_dataset['Boogie'].value_counts().index[0]
#replaced 'T' with most frequent value

In [30]:
from google.colab import files
train_dataset['Ticket'].to_csv('ticket.csv',index=False)

files.download('ticket.csv')

In [31]:
# ticket_number=train_dataset['Ticket'].str.extract(r'.*?(\d+).*?(\d+)').astype(float)
# train_dataset['Ticket_number']= pd.concat([
#     ticket_number.loc[ticket_number[0] > ticket_number[1], 0],
#     ticket_number.loc[ticket_number[1] > ticket_number[0], 1]
# ]).sort_index() #first condition selects where right ticket is at 1st column and second condition where is it at 2nd column.
#                 #now concatenates put them over one another
#                 #indexing value is as it is and through sort_index we give it a rightful order
# better solution came yo!

In [32]:
train_dataset['Ticket_number']=train_dataset['Ticket'].str.extract(r'(\d+)$')
#$ means this pattern of digits must be at end
# if ^(\d)+ means this digit should occur at beginning.

In [33]:
train_dataset.groupby('Ticket_number')['PassengerId'].value_counts()

Ticket_number  PassengerId
10482          284            1
110152         258            1
               505            1
               760            1
110413         263            1
                             ..
8475           653            1
851            154            1
9234           301            1
9549           11             1
               395            1
Name: count, Length: 887, dtype: int64

In [34]:
train_dataset.groupby('Ticket_number')['Survived'].agg(['count', 'mean']).sort_values(by='count',ascending=False)

               count      mean
Ticket_number
347082             7  0.000000
1601               7  0.714286
2343               7  0.000000
347088             6  0.000000
3101295            6  0.000000
...              ...       ...
111369             1  1.000000
111320             1  0.000000
111240             1  0.000000
110813             1  1.000000
110564             1  1.000000

[678 rows x 2 columns]

In [35]:
train_dataset.groupby('Ticket_number')['PassengerId'].agg(['count']).sort_values(by='count',ascending=False)

               count
Ticket_number
347082             7
1601               7
2343               7
347088             6
3101295            6
...              ...
111369             1
111320             1
111240             1
110813             1
110564             1

[678 rows x 1 columns]

In [36]:
train_dataset['Ticket'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Ticket, Length: 891, dtype: bool

In [37]:
train_dataset['Fare'].std()

49.693428597180905

In [38]:
train_dataset['Fare'].mean()

np.float64(32.204207968574636)

In [39]:
train_dataset['Fare'].quantile(0.75)-train_dataset['Fare'].quantile(0.25)

np.float64(23.0896)

In [40]:
train_dataset['Fare'].quantile(0.25)

np.float64(7.9104)

In [41]:
train_dataset['Fare'].quantile(0.75)

np.float64(31.0)

In [42]:
train_dataset['Fare'].quantile(0.90)-train_dataset['Fare'].quantile(0.75)

np.float64(46.958299999999994)

In [43]:
from statsmodels import robust

In [44]:
robust.scale.mad(train_dataset['Fare'])

np.float64(10.236182237006377)

In [45]:
train_dataset['Fare'].std()

49.693428597180905

In [46]:
og_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
from sklearn.base import TransformerMixin, BaseEstimator

In [48]:
class TitanicEngineer(TransformerMixin, BaseEstimator):
  def __init__(self,X):
    self.X=X


  def fit(self,X):
    return self

  def transform(self,X):
    X=X.copy()
    X['Title']=X['Name'].str.extract(r'\,\s+(\w+)')
    X.loc[X['Title'].isin(['Mlle','Ms']),'Title']='Miss'
    X.loc[X['Title'].isin(['Major','Col','Capt']),'Title']='Army'
    X.loc[X['Title'].isin(['Sir','Don','Jonkheer','Lady','the','Mme','Army','Rev','Dr']),'Title']='Rare'
    X['Cabin']=X['Cabin'].str.extract(r'([a-zA-Z])',expand=False)
    X.loc[X['Cabin'].notna() & ~X['Cabin'].isin(['C', 'E', 'G', 'D', 'A', 'B', 'F']),'Cabin']=X['Cabin'].value_counts().index[0]
    return X

In [49]:
titan=TitanicEngineer(og_train)
titan.fit_transform(og_train)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rare
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen 'Carrie'",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr

# **Problems in TitanicEngineer**
1 -> there is no inplace transformation i would have to store the result of titan.fit_transform(og_train)<br>
2 -> earlier in initialization i returned only self and nothing was passed when titanic called  TitanicEngineer() with ot without creating an object i got this error-
TypeError: __init__() should return None, not 'TitanicEngineer'<br>
3 -> how should be the structure and how should fit be and transform and when class is created, as an constructor what function should we pass it?
<br>
# **Answer**<br>
1-> in transform remove x.copy for inplace transform<br>
2-> init is not supposed to return and dont use dataset, it is supposed to intialize parameters only<br>
3-> see next custom

In [50]:
class TitanicDP(TransformerMixin,BaseEstimator):
  def __init__(self):
    pass

  def fit(self,X):
    self.most_occupied_cabin=X['Cabin'].str.extract(r'([a-zA-Z])',expand=False).value_counts().index[0]
    return self

  def transform(self,X):

    X=X.copy()
    X['Title']=X['Name'].str.extract(r'\,\s+(\w+)')
    X.loc[X['Title'].isin(['Mlle','Ms']),'Title']='Miss'
    X.loc[X['Title'].isin(['Major','Col','Capt']),'Title']='Army'
    X.loc[X['Title'].isin(['Sir','Don','Jonkheer','Lady','the','Mme','Army','Rev','Dr']),'Title']='Rare'
    X['Cabin']=X['Cabin'].str.extract(r'([a-zA-Z])',expand=False)
    X.loc[X['Cabin'].notna() & ~X['Cabin'].isin(['C', 'E', 'G', 'D', 'A', 'B', 'F']),'Cabin']=self.most_occupied_cabin
    return X

  #generally both x and y are passed but i have not separated by my dataset till yet so fit only have x

In [73]:
class TitanicDP(TransformerMixin,BaseEstimator):
  def __init__(self):
    pass

  def fit(self,X,y=None):
    self.most_occupied_cabin_=X['Cabin'].str.extract(r'([a-zA-Z])',expand=False).value_counts().index[0]
    return self

  def transform(self,X):

    X=X.copy()
    X['Title']=X['Name'].str.extract(r'\,\s+(\w+)')
    X.loc[X['Title'].isin(['Mlle','Ms']),'Title']='Miss'
    X.loc[X['Title'].isin(['Major','Col','Capt']),'Title']='Army'
    X.loc[X['Title'].isin(['Sir','Don','Jonkheer','Lady','the','Mme','Army','Rev','Dr']),'Title']='Rare'
    X['Cabin']=X['Cabin'].str.extract(r'([a-zA-Z])',expand=False)
    X.loc[X['Cabin'].notna() & ~X['Cabin'].isin(['C', 'E', 'G', 'D', 'A', 'B', 'F']),'Cabin']=self.most_occupied_cabin_
    return X

  #i have decided to pass y in fit
  #most_occupied_cabin_ last underscore to show it is in fit.

In [75]:
columns_to_be_dropped=['PassengerId','Name','Ticket']

In [79]:
def drop_columns(X):
  return X.drop(columns=columns_to_be_dropped)

In [83]:
num_columns=['Age','Fare']

In [86]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector, make_column_transformer

In [88]:
num_pipeline=make_pipeline(SimpleImputer(strategy='median'),StandardScaler())
cat_pipeline=make_pipeline(SimpleImputer(strategy='most_frequent'),OneHotEncoder(handle_unknown='ignore',sparse_output=False))

In [89]:
preprocessing=ColumnTransformer(
    [
        ('num',num_pipeline,num_columns),
        ('cat',cat_pipeline,make_column_selector(dtype_include=object))
    ],
    verbose_feature_names_out=False
)

In [127]:
from sklearn.model_selection import train_test_split

In [90]:
X=og_train.drop(columns=['Survived'])
y=og_train['Survived']

In [128]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [158]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import FunctionTransformer

In [159]:
model_pipeline=Pipeline([
    ('feature_engineer',TitanicDP()),
    ('feature_selection',FunctionTransformer(lambda X:X.drop(columns=columns_to_be_dropped))),
    ('pipeline',preprocessing),
    ('model',RandomForestClassifier(random_state=42))
])

In [160]:
model_pipeline.fit(X_train,y_train)

Pipeline(steps=[('feature_engineer', TitanicDP()),
                ('feature_selection',
                 FunctionTransformer(func=<function <lambda> at 0x7a82ae602700>)),
                ('pipeline',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7a82dbfea510>)],
                                   verbose_feature_names_out=False)),
                ('model', RandomForestClassifier(random_state=42))])

In [161]:
y_pred=(model_pipeline.predict(X_test)[:]>0.5).astype(int)

In [162]:
y_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0])

In [163]:
from sklearn.metrics import accuracy_score

In [164]:
accuracy_score(y_test,y_pred)

0.7597765363128491

In [165]:
model_pipeline[-1].get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [153]:
param_grid=[{
    "model__max_features":[1,10,15,8],
    "model__max_depth":[None,4,6],
    "model__n_estimators":[100,150,50]
}]

In [166]:
from sklearn.model_selection import GridSearchCV

In [167]:
grid_search=GridSearchCV(model_pipeline,param_grid,cv=3,scoring='accuracy')

In [168]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('feature_engineer', TitanicDP()),
                                       ('feature_selection',
                                        FunctionTransformer(func=<function <lambda> at 0x7a82ae602700>)),
                                       ('pipeline',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['Age',
                                                                          'Fare']),
                                                                        ('cat',
                                                                         Pipeline(st...
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x7a82dbfea510>)],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        RandomForestClassifier(random_state=42))]),
             param_grid=[{'model__max_depth': [None, 4, 6],
                          'model__max_features': [1, 10, 15, 8],
                          'model__n_estimators': [100, 150, 50]}],
             scoring='accuracy')

In [171]:
grid_results=pd.DataFrame(grid_search.cv_results_)

In [174]:
grid_results.sort_values(by='mean_test_score',ascending=False,inplace=True)

In [175]:
grid_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__max_features,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
28,0.219391,0.007881,0.022697,0.000574,6,10,150,"{'model__max_depth': 6, 'model__max_features':...",0.789916,0.814346,0.822785,0.809016,0.013938,1
27,0.144543,0.003357,0.017770,0.001010,6,10,100,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.814346,0.822785,0.806214,0.017803,2
29,0.083137,0.006157,0.015168,0.000186,6,10,50,"{'model__max_depth': 6, 'model__max_features':...",0.789916,0.814346,0.814346,0.806203,0.011516,3
6,0.176130,0.004548,0.018871,0.000504,None,15,100,"{'model__max_depth': None, 'model__max_feature...",0.794118,0.789030,0.835443,0.806197,0.020784,4
8,0.097051,0.004655,0.015726,0.000085,None,15,50,"{'model__max_depth': None, 'model__max_feature...",0.794118,0.784810,0.839662,0.806197,0.023967,4
15,0.180193,0.032897,0.020075,0.003760,4,10,100,"{'model__max_depth': 4, 'model__max_features':...",0.773109,0.801688,0.835443,0.803413,0.025477,6
35,0.157156,0.036482,0.025205,0.007724,6,8,50,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.805907,0.822785,0.803402,0.016942,7
31,0.283251,0.078907,0.025764,0.006761,6,15,150,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.805907,0.822785,0.803402,0.016942,7
33,0.243638,0.017343,0.031041,0.002207,6,8,100,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.805907,0.822785,0.803402,0.016942,7
16,0.199339,0.006510,0.021277,0.000800,4,10,150,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.810127,0.827004,0.802013,0.024402,10
19,0.213777,0.004752,0.021164,0.000867,4,15,150,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.805907,0.831224,0.802013,0.025589,10
30,0.159277,0.003684,0.018493,0.001207,6,15,100,"{'model__max_depth': 6, 'model__max_features':...",0.777311,0.805907,0.822785,0.802001,0.018769,12
25,0.176405,0.002142,0.019944,0.000705,6,1,150,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.805907,0.818565,0.801995,0.015378,13
18,0.146767,0.003209,0.017739,0.000377,4,15,100,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.797468,0.835443,0.800606,0.027253,14
20,0.083007,0.001875,0.015637,0.000366,4,15,50,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.810127,0.822785,0.800606,0.023002,14
17,0.081622,0.006476,0.015733,0.000825,4,10,50,"{'model__max_depth': 4, 'model__max_features':...",0.773109,0.810127,0.818565,0.800600,0.019742,16
24,0.131099,0.003554,0.016656,0.000842,6,1,100,"{'model__max_depth': 6, 'model__max_features':...",0.777311,0.805907,0.818565,0.800594,0.017256,17
2,0.080406,0.000755,0.015355,0.000785,None,1,50,"{'model__max_depth': None, 'model__max_feature...",0.789916,0.801688,0.810127,0.800577,0.008288,18
3,0.162289,0.000985,0.020773,0.002767,None,10,100,"{'model__max_depth': None, 'model__max_feature...",0.789916,0.780591,0.831224,0.800577,0.022002,18
13,0.272497,0.014220,0.027159,0.002920,4,1,150,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.801688,0.827004,0.799200,0.023783,20
32,0.140744,0.003268,0.020662,0.000978,6,15,50,"{'model__max_depth': 6, 'model__max_features':...",0.773109,0.805907,0.818565,0.799194,0.019155,21
34,0.310339,0.084730,0.028855,0.005871,6,8,150,"{'model__max_depth': 6, 'model__max_features':...",0.781513,0.805907,0.810127,0.799182,0.012612,22
7,0.250008,0.004924,0.023891,0.002078,None,15,150,"{'model__max_depth': None, 'model__max_feature...",0.785714,0.784810,0.827004,0.799176,0.019681,23
12,0.181511,0.016689,0.020593,0.000929,4,1,100,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.801688,0.822785,0.797793,0.022167,24
22,0.192579,0.005262,0.019948,0.000694,4,8,150,"{'model__max_depth': 4, 'model__max_features':...",0.764706,0.805907,0.818565,0.796393,0.022994,25
14,0.106651,0.008157,0.019070,0.002521,4,1,50,"{'model__max_depth': 4, 'model__max_features':...",0.764706,0.801688,0.822785,0.796393,0.024004,26
26,0.075223,0.007521,0.013758,0.000639,6,1,50,"{'model__max_depth': 6, 'model__max_features':...",0.777311,0.805907,0.805907,0.796375,0.013480,27
4,0.236968,0.017137,0.026523,0.004827,None,10,150,"{'model__max_depth': None, 'model__max_feature...",0.781513,0.780591,0.827004,0.796369,0.021666,28
5,0.093544,0.001825,0.016945,0.001045,None,10,50,"{'model__max_depth': None, 'model__max_feature...",0.785714,0.784810,0.818565,0.796363,0.015704,29
23,0.073886,0.000595,0.013863,0.000481,4,8,50,"{'model__max_depth': 4, 'model__max_features':...",0.768908,0.805907,0.810127,0.794980,0.018517,30
21,0.136418,0.002911,0.016650,0.000216,4,8,100,"{'model__max_depth': 4, 'model__max_features':...",0.773109,0.797468,0.814346,0.794975,0.016927,31
0,0.246313,0.015598,0.032360,0.003012,None,1,100,"{'model__max_depth': None, 'model__max_feature...",0.781513,0.789030,0.810127,0.793556,0.012112,32
1,0.289060,0.068674,0.027445,0.006233,None,1,150,"{'model__max_depth': None, 'model__max_feature...",0.785714,0.784810,0.810127,0.793550,0.011727,33
11,0.087748,0.001796,0.014784,0.000679,None,8,50,"{'model__max_depth': None, 'model__max_feature...",0.794118,0.767932,0.814346,0.792132,0.019000,34
10,0.224878,0.004967,0.023050,0.000806,None,8,150,"{'model__max_depth': None, 'model__max_feature...",0.785714,0.763713,0.822785,0.790737,0.024376,35
9,0.157696,0.001991,0.020035,0.001979,None,8,100,"{'model__max_depth': None, 'model__max_feature...",0.785714,0.763713,0.822785,0.790737,0.024376,35

In [176]:
grid_search.best_params_

{'model__max_depth': 6, 'model__max_features': 10, 'model__n_estimators': 150}

In [177]:
grid_search.best_score_

np.float64(0.809015589358106)

In [179]:
best_model=grid_search.best_estimator_

In [182]:
best_model['model'].feature_importances_

array([0.12977091, 0.18304347, 0.23449483, 0.18608386, 0.00226614,
       0.00327665, 0.04970622, 0.00555696, 0.01696914, 0.00173017,
       0.00215007, 0.01345794, 0.0076222 , 0.01315609, 0.01036382,
       0.01128523, 0.10512227, 0.01933523, 0.00460881])

In [192]:
pd.DataFrame(sorted(zip(best_model['pipeline'].get_feature_names_out(),best_model['model'].feature_importances_)))

               0         1
0            Age  0.129771
1        Cabin_A  0.002266
2        Cabin_B  0.003277
3        Cabin_C  0.049706
4        Cabin_D  0.005557
5        Cabin_E  0.016969
6        Cabin_F  0.001730
7        Cabin_G  0.002150
8     Embarked_C  0.013458
9     Embarked_Q  0.007622
10    Embarked_S  0.013156
11          Fare  0.183043
12    Sex_female  0.234495
13      Sex_male  0.186084
14  Title_Master  0.010364
15    Title_Miss  0.011285
16      Title_Mr  0.105122
17     Title_Mrs  0.019335
18    Title_Rare  0.004609

In [193]:
y_pred=best_model.predict(og_test)

In [196]:
submission=pd.DataFrame({
    'PassengerID':og_test['PassengerId'],
    "Survived": best_model.predict(og_test)
})

In [198]:
submission.to_csv('submission.csv',index=False)

In [199]:
from google.colab import files

In [200]:
files.download("submission.csv")